#                                                 🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥
#                                                💻Scavenger Hunt Config💻
#                                                   🔥Coded By Mike3132🔥
#                                                💻Scavenger Hunt Config💻
#                                                 🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥

Version: 'Version 1.0'
ConfigVersion: '1.0'
##### WARNING: DO NOT CHANGE ANYTHING ABOVE THIS LINE IT WILL BREAK THE PLUGIN!#####

#✍✍✍✍✍Permissions✍✍✍✍✍
#ADMIN PERMISSIONS
#ScavengerHunt.Command.Hunt -> Permission to use admin only commands
#ScavengerHunt.Command.Admin -> Permission to enter and exit the admin mode for placing a break heads
#ScavengerHunt.Command.Admin.Reset -> Permission to reset a target players head count
#ScavengerHunt.Command.Admin.Placed -> Permission to list and teleport to all heads placed in the world
#ScavengerHunt.Command.Admin.Total -> Permission to list the amount of all heads in the current world
#ScavengerHunt.Command.Admin.Compass -> Permission to give the compass item
#ScavengerHunt.Command.Admin.ListOther -> Permission to view the amount of heads target player has found
#ScavengerHunt.Command.Admin.Clear -> Permission to clear all heads placed in the current world

#PLAYER PERMISSIONS
#ScavengerHunt.Command.Heads -> Permission to use player commands
#ScavengerHunt.Command.Heads.Found -> Permission to see how many heads they have found
#ScavengerHunt.Command.Heads.Near -> Permission to see if there is any heads placed nearby the player
#✍✍✍✍✍Permissions✍✍✍✍✍

#✍✍✍✍✍Placeholders✍✍✍✍✍
#These can be use anywhere outside the plugin, including in a playerlist or scoreboard plugin.
#%ScavengerHunt_Heads_Found% -> Shows the player how many heads that they have found
#%ScavengerHunt_Heads_Total_World% -> Shows the player the total amount of placed heads in their current world
#✍✍✍✍✍Placeholders✍✍✍✍✍

#####You can Modify the following how you wish#####

#➳➳➳➳➳ Head Item ➳➳➳➳➳
#This is the head database id that the head will become, You can find the heads and their id's here > https://minecraft-heads.com
Hdb-Head-Id: "63573"

#This is the name of the head that will be displayed in the inventory
Head-Name-Inventory: "&6Spooky Ghost Head"

#This is the lore of the head that will be displayed in the inventory
Head-Lore-List:
  - '&eThis is a custom head'
  - ''
  - '&2Place this in the world to begin the hunt'

#➳➳➳➳➳ Compass Item ➳➳➳➳➳
#Should we enable the custom compass item
Compass-Item-Enabled: true

#Should the compass have uses?
#If this is enabled when a player clicks a compass it will remove 1 custom compass from their inventory stack
Infinite-Compass: true

#This is the distance to the nearest head a player needs to be for the compass to work
Compass-Distance: 5

#This is the name of the compass item
Compass-Name: "&5Head Finder"

#This is the lore of the compass (You need to manually set the amount of blocks the compass works with in the lore)
Compass-Lore-List:
  - '&eRight click this compass to find nearby heads'
  - ''
  - '&2Only works if you are within 5 blocks of a head'

#➳➳➳➳➳ Armorstand ➳➳➳➳➳
#Should we spawn an armorstand when the player claims a head
Armorstand-Animation: true

#Should we play a sound when the player claims a head
Armorstand-Sound: true

#This is the message that shows above the armorstand when the animation plays and is enabled
Armorstand-Message: "&6Spooky"


#➳➳➳➳➳ Player Options ➳➳➳➳➳
#Should the player receive a message when they click on a head. This message can be configured in the messages.yml file
Player-Messages-Enabled: true

#Should we give a reward for every head a player clicks?
EveryClickRewardBoolean: true

#What is the reward we should give? (Please use your /give command syntax)
EveryClickReward:
  - "broadcast %playerName% &2found a head"
  - "give %playerName% stone 1"
  - "give %playerName% diamond 3"


#Should we run a command when a player has found all the heads?
AllHeadsFoundBoolean: true

#What commands should be run when a player finds all the heads
AllHeadsFoundReward:
  - "broadcast %playerName% &4Has found all the heads"
  - "give %playerName% beacon 1"
  - "give %playerName% netherite_block 64"



#See messages.yml for all configurable plugin messages
#♏ If you have any questions please join my discord, open a support ticket and @Mike3132
#♏ https://discord.gg/ePQGvQuzG3
#♏ Thanks for downloading and have a wonderful day

#♛♛♛♛♛ END OF CONFIG ♛♛♛♛♛
#This is the default config file.