name: ScavengerHunt
version: '${project.version}'
main: net.resolutemc.scavengerhunt.ScavengerHunt
api-version: '1.20'
depend:
  - HeadDatabase
  - PlaceholderAPI
commands:
  Hunt:
    description: Main admin command
    permission: ScavengerHunt.Command.Hunt
  Heads:
    description: Main player command
    permission: ScavengerHunt.Command.Heads